### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#1]
## 💰 Motivation

Users can expand their vocabulary. 

## 📐 Plan

Allow users to view homepage that gives them the option to generate a word of the day, view a list of words from previous days, and search a word of their liking.

## 🖼️ Wireframe
<img src="https://user-images.githubusercontent.com/77419144/108884280-40b6fb80-75bb-11eb-9868-ad33cfa7ad8d.png" width ="250">

## ✅ Task List

- [x] Create an icon with heading/subheading
- [x] Add buttons to view a random word and word list
- [x] Add search bar & button
- [x] Add API to JS file
- [x] Update CSS to match wireframe
