### ISSUE TITLE
User can save and view previous word-of-the-days

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#10]
## ✅ Task List

- [x] Create a word list display
- [x] Create a dom tree so words can be populated
- [x] Add an event listener to the word-list button to view word list page
- [x]   Add an event listener to the save button on the definition page
- [x] Put the random values into a new object.
- [x] Add the nextId to the object.
- [x] Increment the nextId on the data model.
- [x] Prepend the new object to the entries in the data model.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors.
