### ISSUE TITLE
issue-7-user-interface

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#15]
##Task List

- [x] Add cursor to buttons & links
- [x] Fix mobile landscape view
- [x] Add description to word-list page to let users can click click on word to view definition
