### ISSUE TITLE
User can view word-of-the-day

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#2]
## ✅ Task List

- [x] Create navigation bar
- [x] Add eventListener 'click' to 'Home' to view the home page
- [x] Create heading and word-of the-day containers
- [x] Create a function to generate random word
- [x] Create two buttons (learn it & new word)
- [x] Add eventListener 'click' to "New Word" to get a new word-of-the-day
- [x] Update CSS

**Comment by lisadoann** [comment]
## ✅ Task List

- [ ] Create navigation bar
- [ ] Add eventListener 'click' to 'Home' to view the home page
- [ ] Create heading and word-of the-day containers
- [ ] Create a function to generate random word
- [ ] Create two buttons (learn it & new word)
- [ ] Add eventListener 'click' to "Learn It" to view definition. -> will save to list 
- [ ] Add eventListener 'click' to "New Word" to get a new word-of-the-day
- [ ] Update CSS
