### ISSUE TITLE
User can search for any words

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#5]
## ✅ Task List

- [x] Add eventListener to form -- input will get definition & show definition view
- [x] Add modal
- [x] Modal will let user know that definition can not be found
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors.
