### ISSUE TITLE
User can view word definition

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/vocab#6]
## ✅ Task List

- [x] Added event listener to the "Learn it" button.
- [x] Create a definition page to display like the wireframe
- [x]  Add XMLHttpRequest to get definition
- [x] Add exit button
- [x] Exit Button will go to homepage
